.\" Process this file with
.\" groff -man -Tascii ogginfo.1
.\"
.TH ogginfo 1 "July 8, 2001" "" "Vorbis Tools"

.SH NAME
ogginfo \- gives information about Ogg files.

.SH SYNOPSIS
.B ogginfo
.I file1.ogg
.B ...
.I fileN.ogg

.SH DESCRIPTION
.B ogginfo
reads one or more Ogg files and decodes the comments contained within, writing
them to standard output, in a "attribute=value" format, one per line.
The first attribute printed will always be the
.B filename
of the stream. 
.B ogginfo
cannot accept URLs.

In addition to the comments,
.B ogginfo
will also print the following attributes for each logical bitstream within the file:
.RS
.IP serial
The serial number of the logical bitstream.
.IP header_integrity
"pass" if the header is intact, and "fail" if it is corrupted.
.IP stream_integrity
"pass" if the stream contains no bad packets or holes (not counting the last 
packet), and "fail" otherwise.
.IP stream_truncated
"true" if the last good packet in the stream is not marked as the last packet
and "false" if the stream is complete.
.IP vendor
The vendor string of the encoder used to make this stream.
.IP bitrate_upper
The upper bitrate limit of the stream, or "none" if not set.
.IP bitrate_nominal
The "target" bitrate of the stream, or "none" if not set.
.IP bitrate_lower
The lower bitrate limit of the stream, or "none" if not set.
.IP bitrate_average
The average bitrate of the stream.
.IP length
Length of of the file in seconds.
.IP playtime
Playing time in a humanly-readable MM:SS format.
.RE

At the end of each file,
.B ogginfo
will also print:
.RS
.IP total_playtime
The total playing time for the entire file in seconds.
.RE

.SH OPTIONS
None.

.SH BUGS

Although
.B ogginfo 
properly handles chained bitstreams, it cannot handle multiplexed
logical bitstreams

.SH AUTHORS

.br
JAmes Atwill <ogg@linuxstuff.org>
.br
Stan Seibert <indigo@aztec.asu.edu>
