.\" Process this file with
.\" groff -man -Tascii vorbiscomment.1
.\"
.TH VORBISCOMMENT 1 "December 21, 2001" Xiphophorus "Vorbis Tools"

.SH NAME
vorbiscomment \- edits Ogg Vorbis comments

.SH SYNOPSIS
.B vorbiscomment
.RB [ -l ]
.I file.ogg
.br
.B vorbiscomment
.B -a
.B [ -t \*(lqtag=value\*(rq ]
.I in.ogg
.I out.ogg
.br
.B vorbiscomment
.B -w
.I in.ogg
.I out.ogg

.SH DESCRIPTION
.B vorbiscomment
reads, modifies, and appends Ogg Vorbis audio files tags.

.SH OPTIONS
.IP "-a"
Append comments.
.IP "-c"
Take comments from a file.
.IP "-h"
Show command help.
.IP "-l"
List the comments.
.IP "-q"
Quiet mode.  No messages are displayed.
.IP "-t tag=value"
.IP "-w"
Modify comments.

.\" .SH EXAMPLES
.\" Examples go here

.SH AUTHORS

.TP
Program Authors:
.br
Michael Smith <msmith@labyrinth.net.au>
.br
Ralph Giles <giles@ashlu.bc.ca>
.br

.TP
Manpage Author:
.br
Christopher L Cheney <ccheney@debian.org>
