.\" Process this file with
.\" groff -man -Tascii vcut.1
.\"
.TH VCUT 1 "December 21, 2001" "Xiph.org Foundation" "Vorbis Tools"

.SH NAME
vcut \- cuts Ogg Vorbis files

.SH SYNOPSIS
.B vcut
.I infile.ogg
.I outfile1.ogg
.I outfile2.ogg
.I cutpoint

.SH DESCRIPTION
.B vcut
reads an Ogg Vorbis audio file and splits it at the given cutpoint, which is a
sample number.

.SH AUTHORS

.TP
Program Author:
Michael Smith <msmith@labyrinth.net.au>

.TP
Manpage Author:
Christoper L Cheney <ccheney@debian.org>
